name: CI Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Build website
        run: bun run build

  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Check repository with biome
        run: bun check

  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Check TypeScript types
        run: bun run tsc --noEmit
